---
# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: 70-helm_csi_cephfs-install | all
  hosts: all
  remote_user: root
  become: true

- name: 70-helm_csi_cephfs-install | ceph_mon
  hosts: ceph_mon
  remote_user: root
  become: true
  tasks:
    - name: ceph health detail
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          ceph crash archive-all
          ceph health mute AUTH_EMERGENCY_CIPHERS_SET --sticky
          ceph health mute AUTH_INSECURE_CLIENT_KEY_TYPE --sticky
          ceph health mute AUTH_INSECURE_KEYS_ALLOWED --sticky
          ceph health mute AUTH_INSECURE_KEYS_CREATABLE --sticky
          ceph health detail | grep 'HEALTH_OK'
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['ceph_mon'][0]
      register: result
      changed_when: result is not succeeded
      until: result is succeeded
      retries: 60

- name: 70-helm_csi_cephfs-install | kube_master
  hosts: kube_master
  remote_user: root
  become: true
  tasks:
    - name: kubectl get --raw='/readyz?verbose'
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          kubectl get --raw='/readyz?verbose' | grep 'check passed'
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['kube_master'][0]
      register: result
      changed_when: result is not succeeded
      until: result is succeeded
      retries: 60

    - name: kubectl version --output=yaml
      ansible.builtin.command:
        cmd: kubectl version --output=yaml
      register: result
      changed_when: result is not succeeded

    - name: include role
      ansible.builtin.include_role:
        name: helm

    - name: fetch ceph client.csi-cephfs key
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          ceph mon set auth_allowed_ciphers aes,aes256k
          ceph auth get-or-create client.csi-cephfs \
            mds 'allow *' \
            mgr 'allow *' \
            mon 'allow *' \
            osd 'allow *' \
            --key_type=aes >/dev/null 2>&1
          ceph auth get-key client.csi-cephfs \
            --format plain
      args:
        executable: /bin/bash
      delegate_to: "{{ groups['ceph_mon'][0] }}"
      register: ceph_client_user_result
      changed_when: ceph_client_user_result is not succeeded

    - name: include role
      ansible.builtin.include_role:
        name: helm_csi_snapshotter

    - name: include role
      ansible.builtin.include_role:
        name: helm_csi_cephfs
      vars:
        helm_csi_cephfs_user_secret: "{{ ceph_client_user_result.stdout }}"
