---

# Copyright 2023 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: crictl-pull | kube_master:kube_node
  hosts: kube_master:kube_node
  remote_user: root
  become: true
  tasks:
    - name: fetch image list
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s '[[:space:]]' '\n' | sed 's/^docker.io\///g' | sort -u
      args:
        executable: "/bin/bash"
      register: result
      delegate_to: "{{ groups['kube_master'][0] }}"
      changed_when: false
      failed_when: false

    - name: crictl pull image
      ansible.builtin.command:
        cmd: crictl pull {{ item }}
      loop: "{{ result.stdout_lines }}"
      changed_when: result is not succeeded

    - name: fetch untagged image list
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          crictl image | grep -- '<none>' | awk -F' ' '{print $3}'
      args:
        executable: "/bin/bash"
      register: result
      changed_when: false
      failed_when: false

    - name: crictl rmi
      ansible.builtin.command:
        cmd: crictl rmi {{ item }}
      loop: "{{ result.stdout_lines }}"
      changed_when: result is not succeeded
