---
# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: reboot | all:!ansible
  hosts: all:!ansible
  remote_user: root
  become: true
  tasks:
    - name: check
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          cat > /.reboot_command.sh <<\EOF
          #!/bin/bash
          set -euxo pipefail
          if [[ -x "$(command -v kubectl)" ]]; then
            kubectl drain $(hostname) --force --delete-emptydir-data --ignore-daemonsets --disable-eviction
            systemctl stop kubelet.service
            crictl ps -aq | xargs crictl rm
            systemctl stop crio.service
          fi
          if [[ -x "$(command -v ceph)" ]]; then
            umount -lfa -t ceph
            systemctl stop ceph.target
          fi
          reboot
          EOF
          chmod a+x /.reboot_command.sh
          cat > /.test_command.sh <<\EOF
          #!/bin/bash
          set -euxo pipefail
          if [[ -x "$(command -v ceph)" ]]; then
            ceph crash archive-all
            [ $(ceph health detail | grep -c 'HEALTH_OK') -eq 1 ]
          fi
          if [[ -x "$(command -v kubectl)" ]]; then
            kubectl uncordon $(hostname)
            [ $(kubectl get --raw='/readyz?verbose' | grep -c 'check passed') -eq 1 ]
            [ $(kubectl get pod --all-namespaces --no-headers | grep -c -v -E '(Running|Completed)') -eq 0 ]
          fi
          EOF
          chmod a+x /.test_command.sh
          /.test_command.sh
      args:
        executable: /bin/bash
      register: result
      changed_when: result is not succeeded
      until: result is succeeded
      retries: 60

    - name: reboot
      ansible.builtin.reboot:
        connect_timeout: 300
        reboot_timeout: 3600
        pre_reboot_delay: 60
        post_reboot_delay: 60
        reboot_command: /.reboot_command.sh
        test_command: /.test_command.sh
      throttle: 1
      changed_when: false
      failed_when: false

- name: reboot | ansible
  hosts: ansible
  remote_user: root
  become: true
  tasks:
    - name: reboot
      ansible.builtin.reboot:
        connect_timeout: 300
        reboot_timeout: 3600
        pre_reboot_delay: 60
        post_reboot_delay: 60
        test_command: whoami
      throttle: 1
      changed_when: false
      failed_when: false
